apiVersion: v1
kind: Service
metadata:
  name: akhq-service
spec:
  selector:
    app: akhq-kafka-gui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # Use NodePort, ClusterIP, or LoadBalancer based on your setup
