apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080 # Must match the container port in your Deployment
  type: ClusterIP # You can use other types like NodePort or LoadBalancer if needed
