kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-kafka
  labels:
    app: demo-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-kafka
  template:
    metadata:
      labels:
        app: demo-kafka
    spec:
      containers:
      - name: demo-kafka
        image: confluentinc/cp-kafka:7.0.1
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 'demo-zookeeper:2181'
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://:29092,PLAINTEXT_INTERNAL://demo-kafka:9092
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-kafka
spec:
  selector:
    app: demo-kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092