apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-consumer
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: demo-consumer
  template:
    metadata:
      labels:
        app: demo-consumer
    spec:
      containers:
        - name: demo-consumer-container
          image: consumer:latest 
          ports:
            - containerPort: 8080
          env:
            - name: kafka_order_bootstrap-servers
              value: "demo-kafka:9092"
            - name: kafka_order_topic_create-order
              value: "create-order"
            - name: logging_level_root
              value: "info"
            - name: kafka_order_consumer_group-id_notification
              value: "notification"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-consumer
spec:
  selector:
    app: demo-consumer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080 # Must match the container port in your Deployment
  type: ClusterIP # You can use other types like NodePort or LoadBalancer if needed
