apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-zookeeper
  labels:
    app: demo-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-zookeeper
  template:
    metadata:
      labels:
        app: demo-zookeeper
    spec:
      containers:
      - name: demo-zookeeper
        image: confluentinc/cp-zookeeper:7.0.1
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-zookeeper
spec:
  selector:
    app: demo-zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181