apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-akhq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-akhq
  template:
    metadata:
      labels:
        app: demo-akhq
    spec:
      containers:
        - name: akhq-kafka-container
          image: tchiotludo/akhq:latest # Change to the desired AKHQ version/tag
          ports:
            - containerPort: 8080
          env:
            - name: AKHQ_CONFIGS_GLOBAL_BOOTSTRAP_SERVERS
              value: "demo-kafka:9092" # Replace with your Kafka broker address
            - name: AKHQ_CONFIGURATION
              value: |
                akhq:
                  connections:
                    demo-kafka-server:
                      properties:
                        bootstrap.servers: "demo-kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-akhq
spec:
  selector:
    app: demo-akhq
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # Use NodePort, ClusterIP, or LoadBalancer based on your setup
                
