apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  selector:
    app: producer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080 # Must match the container port in your Deployment
  type: ClusterIP # You can use other types like NodePort or LoadBalancer if needed
