apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer-container
          image: producer:latest 
          ports:
            - containerPort: 8080
          env:
            - name: kafka_order_bootstrap-servers
              value: "kafka-service:9092"
            - name: kafka_order_topic_create-order
              value: "create-order"
            - name: logging_level_root
              value: "info"
            - name: auto_create_topics_enable
              value: "true"